# Generated by Django 4.0.2 on 2022-07-01 20:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=20, unique=True)),
                ('server_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('battlEye', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_link', models.URLField(unique=True)),
                ('Character_name', models.CharField(max_length=80)),
                ('auction_start', models.DateTimeField(blank=True, null=True)),
                ('auction_end', models.DateTimeField(blank=True, null=True)),
                ('bid_status', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=24, null=True)),
                ('experience', models.CharField(blank=True, max_length=36, null=True)),
                ('gold', models.CharField(blank=True, max_length=36, null=True)),
                ('vocation', models.CharField(blank=True, max_length=40, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('hp', models.CharField(blank=True, max_length=42, null=True)),
                ('mana', models.CharField(blank=True, max_length=42, null=True)),
                ('capacity', models.CharField(blank=True, max_length=42, null=True)),
                ('speed', models.CharField(blank=True, max_length=42, null=True)),
                ('all_outfit', models.CharField(blank=True, max_length=42, null=True)),
                ('basic_outfit', models.CharField(blank=True, max_length=42, null=True)),
                ('store_outfit', models.IntegerField(blank=True, null=True)),
                ('all_mount', models.CharField(blank=True, max_length=42, null=True)),
                ('basic_mount', models.CharField(blank=True, max_length=42, null=True)),
                ('store_mount', models.IntegerField(blank=True, null=True)),
                ('quantity_charms', models.IntegerField(blank=True, null=True)),
                ('charm_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('charm_point', models.CharField(blank=True, max_length=42, null=True)),
                ('charm_expension', models.BooleanField(blank=True, null=True)),
                ('prey_slot', models.BooleanField(blank=True, null=True)),
                ('quest_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None)),
                ('quantity_quest', models.IntegerField(blank=True, null=True)),
                ('auctions_status', models.CharField(blank=True, max_length=264, null=True)),
                ('commission', models.IntegerField(default=0)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.server')),
            ],
        ),
    ]
