# Generated by Django 4.0.2 on 2022-03-27 16:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=20)),
                ('server_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('battlEye', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_status', models.CharField(max_length=40)),
                ('price', models.BigIntegerField()),
                ('level', models.BigIntegerField()),
                ('experience', models.BigIntegerField()),
                ('gold', models.BigIntegerField()),
                ('vocation', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=10)),
                ('skils', models.JSONField()),
                ('hp', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('all_outfit', models.IntegerField()),
                ('basic_outfit', models.IntegerField()),
                ('store_outfit', models.IntegerField()),
                ('all_mount', models.IntegerField()),
                ('basic_mount', models.IntegerField()),
                ('store_mount', models.IntegerField()),
                ('charm_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('charm_point', models.IntegerField()),
                ('charm_expension', models.BooleanField()),
                ('prey_slot', models.BooleanField()),
                ('quest_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('quantity_quest', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.server')),
            ],
        ),
    ]
